name: Build & test

on: [push, pull_request]

jobs:
  linux:
    uses: przemek83/common/.github/workflows/build-and-test-cpp.yml@main
    with:
      platform: ubuntu-latest
      use-qt: true

#   windows:
#     uses: przemek83/common/.github/workflows/build-and-test-cpp.yml@main
#     with:
#       platform: windows-latest