name: Build & test

on: [push, pull_request]

jobs:
  linux:
    uses: przemek83/common/.github/workflows/build-and-test-cpp.yml@main
    with:
      platform: ubuntu-latest
      use-qt: true
      qt-version: 6.5.*
      qt-host: linux

  windows:
    uses: przemek83/common/.github/workflows/build-and-test-cpp.yml@main
    with:
      platform: windows-latest
      use-qt: true
      qt-version: 6.5.*
      qt-host: windows